import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/components/providers/AuthProvider'
import SmoothScrolling from '@/components/providers/LennisProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <SmoothScrolling>
            {children}
            </SmoothScrolling>
      </AuthProvider>
      </body>
    </html>
  )
}
